config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/', to: 'opinions#index', as: :root
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  post '/create_opinion', to: 'opinions#create', as: :new_opinion
  get '/follow/:followed_id', to: 'followings#create', as: :follow
  delete '/:followed_id', to: 'followings#destroy', as: :unfollow
  get '/like/:opinion_id', to: 'likes#create', as: :like
  delete '/unlike/:opinion_id', to: 'likes#destroy', as: :unlike
  resources :users, except: [:new]
  resources :opinions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/following.rb
class Following < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'

  def self.find_friend_to_unfollow(sender_id, receiver_id)
    Following.where(Follower_id: sender_id).where(Followed_id: receiver_id)[0]
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id', class_name: 'User'
  belongs_to :opinion, foreign_key: 'opinion_id', class_name: 'Opinion'

  def self.find_user_like(user_id, opinion_id)
    Like.where(user_id: user_id).where(opinion_id: opinion_id)[0]
  end
end

app/models/opinion.rb
class Opinion < ApplicationRecord
  belongs_to :auther, class_name: 'User'
  has_many :likes, foreign_key: 'opinion_id', class_name: 'Like'
  validates :text, presence: true

  scope :ordered_by_most_recent, -> { order(created_at: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :opinions, foreign_key: 'auther_id', class_name: 'Opinion'
  has_many :likes, foreign_key: 'user_id', class_name: 'Like'
  has_many :followers, class_name: 'Following', foreign_key: 'follower_id'
  has_many :followed, class_name: 'Following', foreign_key: 'followed_id'

  has_one_attached :Photo
  has_one_attached :CoverIimage

  validates :username, presence: true, uniqueness: true
  validates :fullname, presence: true

  def self.user_followers(id, curr_user_id)
    Following.where(follower_id: id).where.not(followed_id: curr_user_id).order(created_at: :desc).limit(5)
  end

  def self.all_users(user_id)
    User.where('id != ?', user_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?, :authorize

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end

  def authorize
    redirect_to login_path unless logged_in?
  end

  def check_user
    session[:current_user]
  end
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  def create
    Following.create(follower_id: current_user.id, followed_id: params[:followed_id])
    redirect_to user_path(params[:followed_id])
  end

  def destroy
    @followings = Following.find_friend_to_unfollow(current_user.id, params[:follower_id])
    @followings.destroy
    redirect_to user_path(params[:followed_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    Like.create(opinion_id: params[:opinion_id], user_id: current_user.id)
    redirect_to root_path
  end

  def destroy
    @like = Like.find_user_like(current_user.id, params[:opinion_id])
    @like.destroy
    redirect_to root_path
  end
end

app/controllers/opinions_controller.rb
class OpinionsController < ApplicationController
  before_action :authorize

  def index
    @opinion = Opinion.new
    @opinions = post_opinions.includes(:auther).limit(4)
    @users = User.all_users(current_user.id).order('created_at DESC')
  end

  def create
    @opinion = Opinion.new(opinion_params)
    @opinion.auther_id = current_user.id

    if @opinion.save
      flash[:notice] = 'Idea well created'
      redirect_to root_path
    else
      flash[:alert] = 'something went wrong'
      render 'index'
    end
  end

  private

  def post_opinions
    @post_opinions ||= Opinion.all.ordered_by_most_recent.includes(:user)
  end

  def opinion_params
    params.require(:opinion).permit(:text)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(username: params[:session][:username])
    if user
      session[:user_id] = user.id
      flash[:notice] = 'You have successfully logged in'
      redirect_to root_path(user)
    else
      flash.now[:alert] = 'There was something wrong with your login information'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'You have logged out'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = 'Registered successfully please Login'
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @opinions = @user.opinions.order('created_at DESC').limit(5)
    @followers = User.user_followers(params[:id], current_user.id)
  end

  private

  def user_params
    params.require(:user).permit(:username, :fullname, :Photo, :CoverImage)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5.hexdigest(user.username.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: 'gravatar')
  end

  def check_photo(user)
    if user.Photo.attached?
      image_tag(user.Photo, class: 'img')
    else
      content_tag(:div, 'No photo', class: %w[bg_gray circle img-none])
    end
  end

  def check_cover(user)
    image_tag(user.coverIimage, class: 'cover_img') if user.CoverIimage.attached?
  end

  def opinions(opinions)
    @opinions = opinions
    render '/layouts/opinion'
  end

  def follow
    return if current_user.id == @user.id

    if current_user.followed.any? || current_user.include?(follower) { |person| person.followed_id == @user.id }
      link_to unfollow_path(@user), method: :delete, class: 'font-unfollow-icon fas fa-minus-circle fa-2x'
    else
      link_to follow_path(@user), class: 'font-follow-icon fas fa-plus-circle fa-2x'
    end
  end
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/followings/_followto.html.erb
<% @users.each do |user| %>
<%= user.fullname%>
 <%= link_to "follow", follow_path(user_id:user.id),class:"btn btn-info" %>
<%end%> 

app/views/layouts/_opinion.html.erb
<% @opinions.each do |o| %>
<div class="post_card">
<div class="avatar">
<%= check_photo(opinion.auther) %>
</div>
<div>
 <%= link_to  opinion.author.fullname, user_path(opinion.auther),class:"bold"  %>
<p><%= opinion.text%></p>
</div>
</div>
<%end%>

app/views/layouts/_sidebar.html.erb
<div class="side-nav">
  <div class="current-user">
    <div class="picture fol-pro">
      <% if current_user[:Photo].nil? %>
        <%= check_photo current_user %>
      <% else %>
        <%= image_tag current_user.Photo.thumb.url %>
      <% end %>           
    </div>
    <h6><%= current_user.fullname %></h6>
  </div>
  <div class="follow">
    <div class="following-stat-side">
      <div class="stats-1">
        <p class="stat-no"><%= current_user.followed.size %></p>
        <p class="stat-name">Following</p>
      </div>
    </div>
    <div class="followed-stat-side">
      <div class="stats-2">
        <p class="stat-no"><%= current_user.followers.size %></p>
        <p class="stat-name">Followers</p>
      </div>
    </div>
  </div>
  <div class="side-links">
    <div class="home-link links active">
      <i class="fas fa-home"></i>
      <%= link_to 'HOME', root_path, class: "links-path active" %>
    </div>
    <div class="profile-link links">
      <i class="fas fa-user"></i>
      <%= link_to 'PROFILE', user_path(current_user.id), class: "links-path" %>
    </div>
    <div class="logout-link links">
      <i class="fas fa-power-off"></i>
      <%= link_to 'LOGOUT', logout_path, method: :delete, class: "links-path" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterRedesign</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"/>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div>
        <p class="notice text-center text-success"><%= notice %></p>
      </div>
      <% end %>
      <% if flash[:alert] %>
        <div>
          <p class="alert text-center text-danger"><%= alert %></p>
        </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/opinions/_navigation.html.erb
<nav class="nav-bar">
  <i class="fab fa-twitter fa-lg" id="logo"></i>
  <ul>
    <li><i class="fas fa-pen"></i></li>
    <li><i class="fas fa-envelope-square"></i></li>
    <li><i class="fas fa-search"></i></li>
    <li><i class="fas fa-cog"></i></li>
  </ul>
</nav> 

app/views/opinions/index.html.erb
<div class="main-content">
 <%= render '/layouts/sidebar' %>
 <main>
  <%= render 'navigation' %>
  <div class="main-body">
    <div class="tweets">
      <p class="tweets-heading">OPINIONS</p>
      <div class="tweet-form">
        <p>WRITE SOMETHING</p>
        <% if @opinion.errors.full_messages.any? %>
          <% @opinion.errors.full_messages.each do |message| %>
              <p class="text-danger"><%= message %></p>
          <% end %>
        <% end %>
        <%= form_for @opinion, url: new_opinion_path do |f| %>
          <%= f.text_area :text, class: "text-input", placeholder: "Compose new Idea" %>
          <%= f.submit "Save", class: "text-btn" %>
        <% end %>
      </div>
      <div class="tweet-body">
        <p class="tweet-body-header">NEW OPINION</p>
        <% Opinion.all.each do |opinion| %>
          <div class="tweet-avatar">
            <div class="picture hero-img cover">
              <% if opinion.auther[:Photo].nil? %>
                <%= check_photo opinion.auther%>
              <% else %>
                  <div class="picture cover hero-img">
                  <%= check_cover(@user) %>         
                </div>
                <h6><%= user.fullname %></h6>
              <% end %>
            </div>
          </div>
          <div class="tweet-content">
            <h4><%= opinion.auther.fullname %></h4>
            <span><%= sanitize opinion.text %></span>
              <span class="like">
                <% if opinion.likes.any? { |like| like.user_id == current_user.id }%>
                  <%= link_to unlike_path(opinion), method: :delete, class: 'user-1' do %>
                    <i class="fas fa-heart text-danger"></i>
                  <% end %>
                <% else %>
                  <%= link_to like_path(opinion), class: 'user-2' do %>
                    <i class="fas fa-heart text-white"></i>
                  <% end %>
                <% end %>
                <% if opinion.likes.any? %>
                  <p><%= "#{pluralize(opinion.likes.size, 'like')}" %></p>
                <% end %>
            </span>
          </div>
          <div class="clear"></div>
        <% end %>
      </div>
    </div>
    <aside class="who-follow">
      <div class="follow-header">
        <h3 class= "text-primary">WHO TO FOLLOW</h3>
      </div>
      <div class="find-friends">
        <% User.all.each do |user| %>
          <div class="who-follow-profile">
            <div class="picture">
              <%= link_to user_path(user), class: 'user' do %>
                <% unless user[:Photo].nil? %>
                  <div class = "fol-pro">
                    <%= image_tag user.Photo.thumb.url, class: 'photo' %>
                  </div>
                <% else %>
                  <div class = "fol-pro ">
                    <%= check_photo user %>
                  </div>
                <% end %>
                <h6 class = "py-2"><%= user.fullname %></h6>
              <% end %>
            </div>  
          </div>
        <% end %>
      </div>
    </aside>
  </div> 
 </main>
</div>

app/views/opinions/new.html.erb
<div class="p-5 mx-auto signup my-5 border rounded-lg border-info">
<%= form_for @opinion do |f| %>
    <div class="form-group">
    <%= f.text_area :text %><br>
    </div>
    <%= f.submit "Send",class:"btn btn-info" %>
<% end %>
</div> 

app/views/users/new.html.erb
<div class="login-cover text-center">
  <div class="twitter-logo">
      <i class="fab fa-twitter fa-3x"></i>
  </div>
  <h3>Sign Up to Twitter</h3>
</div>
<% if @user.errors.any? %>
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="panel panel-danger">
          <div class="panel-heading">
            <h3><%= pluralize(@user.errors.count, "error") %> prohibited this user to be saved:</h3>
            <div class="panel-body">
              <ul>
                <% @user.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>      
      </div>
    </div>
<% end %>

<%= form_for (@user), :url => users_path, :html => {class: "text-center login-form"} do |f| %>
  <div class="form-label">
    <%= f.label :username, class: "username-label" %>
  </div>
  <div class="form-input">
    <%= f.text_field :username, class: "username-input", placeholder: "Enter Username" %>
  </div>

  <div class="form-label">
    <%= f.label :fullname, class: "Fullname-label" %>
  </div>
  <div class="form-input">
    <%= f.text_field :fullname, class: "Fullname-input", placeholder: "Enter Fullname" %>
  </div>

  <div class="form-label">
    <%= f.label :Photo, class: "Photo-label" %>
  </div>
  <div class="form-input">
    <%= f.file_field :Photo, class: "Photo-input text-center" %>
  </div>

  <div class="form-label">
    <%= f.label :CoverImage, class: "cover-image-label" %>
  </div>
  <div class="form-input">
    <%= f.file_field :CoverImage, class: "cover-image-input text-center" %>
  </div>

  <div class="form-actions">
    <%= f.submit "Sign Up",  class: "btn btn-primary signup-btn"%>    
  </div>
  <%= link_to "homepage on twitter", root_path %>
<% end %>

app/views/users/show.html.erb
<div class="main-content">
 <%= render 'layouts/sidebar' %>
 <main>
  <%= render 'opinions/navigation' %>
  <div class="main-user-body">
    <div class="user-tweet">
      <div class="hero-img">
        <% unless @user[:CoverImage].nil? %>
          <div class="picture cover hero-img">
            <%= check_cover(@user) %>         
          </div>
        <% else %>
          <img src="https://via.placeholder.com/150" alt="">
        <% end %>
      </div>
      <div class="user-body">
        <p class="user-body-header">ALL OPINIONS</p>
        <% @opinions.each do |opinion| %>
          <div class="user-avatar cover">
            <div class="picture cover hero-img">
              <%= check_photo(@user) %>         
            </div>
          </div>
          <div class="user-content">
            <h4><%= opinion.auther.fullname %></h4>
            <span><%= opinion.text %></span>
            <span class="like">
      
            <div class="clear"></div>
          </div>
        <% end %>
      </div>
    </div>
    <div  class="user-profile">
     <div class="profile-container">
        <div class="follow-icon">
          <% unless current_user.id == @user.id %>
              <% if current_user.followers.any? { |person| person.followed_id == @user.id }%>
                <%= link_to unfollow_path(@user), method: :delete, class: "font-unfollow-icon" do %>
                  <i class="fas fa-minus-circle fa-2x"></i>
                <% end %>
              <%else%>
                <%= link_to follow_path(@user), class: "font-follow-icon" do %>
                  <i class="fas fa-plus-circle fa-2x"></i>
                <% end %>
              <% end %>
          <% end %>
          <div class="picture hero-img">
            <% unless @user[:Photo].nil? %>
              <%= check_photo(@user) %>
            <% else %>
              <%= check_photo @user %>
            <% end %>
          </div>
          <i class="fas fa-list fa-lg text-primary pt-2"></i>
        </div>
        <div class="profile-details text-center">
          <h5><%= @user.fullname.upcase %></h5>
          <h6>@<%= @user.username %></h6>
        </div> 
      </div>
      <div class="user-stat">
        <div class="opinion-stat">
          <div class="stats-1">
            <p class="stat-no"><%= @opinions.size %></p>
            <p class="stat-name">OPINION</p>
          </div>
        </div>
        <div class="following-stat">
          <div class="stats-1">
            <p class="stat-no"><%= @user.followed.size %></p>
            <p class="stat-name">Following</p>
          </div>
        </div>
        <div class="followed-stat">
          <div class="stats-3">
            <p class="stat-no"><%= @user.followers.size %></p>
            <p class="stat-name">Followers</p>
          </div>
        </div>
      </div>
      <div class="followers-section">
        <div class="followers-header">
          <p>FOLLOWED BY</p>
        </div>
        <div class="my-followers">
            <% @followers.each do |follower| %>
              <div class="follower-profile">
                <div class="follower-avatar">
                  <% unless follower.follower[:Photo].nil? %>
                    <%= image_tag follower.follower.Photo.thumb.url %>
                  <% else %>
                    <%= check_photo follower.follower %>
                  <% end %>
                  <h6><%= follower.follower.fullname %></h6>
                </div>
                <% if current_user.followers.any? { |person| person.followed_id == follower.follower.id }%>
                  <%= link_to unfollow_path(follower.followed), method: :delete, class: "follow-icons" do %>
                      <i class="fas fa-minus-circle fa-2x"></i>
                  <% end %>
                <%else%>
                  <%= link_to follow_path(follower.follower), class: "follow-icons" do %>
                    <i class="fas fa-plus-circle fa-2x"></i>
                  <% end %>
                <% end %>
              </div>
            <% end %>
          </div>
      </div>
    </div>
  </div>
 </main>
</div>